// This file is part of olympus-xmp. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/olympus-xmp/master/COPYRIGHT. No part of olympus-xmp, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
// Copyright © 2022 The developers of olympus-xmp. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/olympus-xmp/master/COPYRIGHT.


/// Must be kept in ascending sort order.
///
/// Extracted from the PDF for UNSD Series M, Nº49 Revision 4 (1999).
///
/// The only entries which do not have a `Revision3Or4Abbreviations` are:-
/// * Taiwan Province of China.
/// The only entries which do not have an `Iso3166Dash1Alpha3Code` are:-
/// * Channel Islands (formerly had ISO 3166-1 alpha 3 code `CHL`.
/// * Areas not elsewhere specified.
//  * Areas not specified.
/// TODO: Non-English names.
/// There are no French abbreviations.
/// There are no 4 character abbreviations.
/// There are no 8 character abbreviations.
pub(super) const NamesAndAbbreviationsForCountriesRevision4: [(M49Code, StaticEnglishName, Option<Revision3Or4Abbreviations>, OptionalIso3166Dash1AlphaCodes); 233] =
{
	#[inline(always)]
	const fn name_and_abbreviation_for_country_revision_4(m49_code: StaticM49Code, english_name: StaticEnglishName, twelve_character_abbreviation: Option<StaticAbbreviation>, iso_3166_alpha_codes: Option<(StaticIso3166Dash1Alpha2Code, StaticIso3166Dash1Alpha3Code)>) -> (M49Code, StaticEnglishName, Option<Revision3Or4Abbreviations>, OptionalIso3166Dash1AlphaCodes)
	{
		(M49Code::from(m49_code), english_name, twelve_character_abbreviation.map(const_revision_3_or_4_abbreviations), iso_3166_alpha_codes.map(const_iso_3166_dash_1_alpha_codes_from))
	}
	
	[
		name_and_abbreviation_for_country_revision_4(b"004", "Afghanistan", Some(b"AFGHANISTAN"), Some((b"AF", b"AFG"))),
		name_and_abbreviation_for_country_revision_4(b"008", "Albania", Some(b"ALBANIA"), Some((b"AL", b"ALB"))),
		name_and_abbreviation_for_country_revision_4(b"012", "Algeria", Some(b"ALGERIA"), Some((b"DZ", b"DZA"))),
		name_and_abbreviation_for_country_revision_4(b"016", "American Samoa AMER", Some(b"SAMOA"), Some((b"AS", b"ASM"))),
		name_and_abbreviation_for_country_revision_4(b"020", "Andorra", Some(b"ANDORRA"), Some((b"AD", b"AND"))),
		name_and_abbreviation_for_country_revision_4(b"024", "Angola", Some(b"ANGOLA"), Some((b"AO", b"AGO"))),
		name_and_abbreviation_for_country_revision_4(b"028", "Antigua and Barbuda", Some(b"ANTIGUA,BARB"), Some((b"AG", b"ATG"))),
		name_and_abbreviation_for_country_revision_4(b"031", "Azerbaijan", Some(b"AZERBAIJAN"), Some((b"AZ", b"AZE"))),
		name_and_abbreviation_for_country_revision_4(b"032", "Argentina", Some(b"ARGENTINA"), Some((b"AR", b"ARG"))),
		name_and_abbreviation_for_country_revision_4(b"036", "Australia", Some(b"AUSTRALIA"), Some((b"AU", b"AUS"))),
		name_and_abbreviation_for_country_revision_4(b"040", "Austria", Some(b"AUSTRIA"), Some((b"AT", b"AUT"))),
		name_and_abbreviation_for_country_revision_4(b"044", "Bahamas", Some(b"BAHAMAS"), Some((b"BS", b"BHS"))),
		name_and_abbreviation_for_country_revision_4(b"048", "Bahrain", Some(b"BAHRAIN"), Some((b"BH", b"BHR"))),
		name_and_abbreviation_for_country_revision_4(b"050", "Bangladesh", Some(b"BANGLADESH"), Some((b"BD", b"BGD"))),
		name_and_abbreviation_for_country_revision_4(b"051", "Armenia", Some(b"ARMENIA"), Some((b"AM", b"ARM"))),
		name_and_abbreviation_for_country_revision_4(b"052", "Barbados", Some(b"BARBADOS"), Some((b"BB", b"BRB"))),
		name_and_abbreviation_for_country_revision_4(b"056", "Belgium", Some(b"BELGIUM"), Some((b"BE", b"BEL"))),
		name_and_abbreviation_for_country_revision_4(b"060", "Bermuda", Some(b"BERMUDA"), Some((b"BM", b"BMU"))),
		name_and_abbreviation_for_country_revision_4(b"064", "Bhutan", Some(b"BHUTAN"), Some((b"BT", b"BTN"))),
		name_and_abbreviation_for_country_revision_4(b"068", "Bolivia", Some(b"BOLIVIA"), Some((b"BO", b"BOL"))),
		name_and_abbreviation_for_country_revision_4(b"070", "Bosnia and Herzegovina", Some(b"BOSNIA HERZG"), Some((b"BA", b"BIH"))),
		name_and_abbreviation_for_country_revision_4(b"072", "Botswana", Some(b"BOTSWANA"), Some((b"BW", b"BWA"))),
		name_and_abbreviation_for_country_revision_4(b"076", "Brazil", Some(b"BRAZIL"), Some((b"BR", b"BRA"))),
		name_and_abbreviation_for_country_revision_4(b"084", "Belize", Some(b"BELIZE"), Some((b"BZ", b"BLZ"))),
		name_and_abbreviation_for_country_revision_4(b"090", "Solomon Islands", Some(b"SOLOMON IS"), Some((b"SB", b"SLB"))),
		name_and_abbreviation_for_country_revision_4(b"092", "British Virgin Islands", Some(b"BR.VIRGIN IS"), Some((b"VG", b"VGB"))),
		name_and_abbreviation_for_country_revision_4(b"096", "Brunei Darussalam", Some(b"BRUNEI DARSM"), Some((b"BN", b"BRN"))),
		name_and_abbreviation_for_country_revision_4(b"100", "Bulgaria", Some(b"BULGARIA"), Some((b"BG", b"BGR"))),
		name_and_abbreviation_for_country_revision_4(b"104", "Myanmar", Some(b"MYANMAR"), Some((b"MM", b"MMR"))),
		name_and_abbreviation_for_country_revision_4(b"108", "Burundi", Some(b"BURUNDI"), Some((b"BI", b"BDI"))),
		name_and_abbreviation_for_country_revision_4(b"112", "Belarus", Some(b"BELARUS"), Some((b"BY", b"BLR"))),
		name_and_abbreviation_for_country_revision_4(b"116", "Cambodia", Some(b"CAMBODIA"), Some((b"KH", b"KHM"))),
		name_and_abbreviation_for_country_revision_4(b"120", "Cameroon", Some(b"CAMEROON"), Some((b"CM", b"CMR"))),
		name_and_abbreviation_for_country_revision_4(b"124", "Canada", Some(b"CANADA"), Some((b"CA", b"CAN"))),
		name_and_abbreviation_for_country_revision_4(b"132", "Cape Verde", Some(b"CAPE VERDE"), Some((b"CV", b"CPV"))),
		name_and_abbreviation_for_country_revision_4(b"136", "Cayman Islands", Some(b"CAYMAN IS"), Some((b"KY", b"CYM"))),
		name_and_abbreviation_for_country_revision_4(b"140", "Central African Republic", Some(b"CENT.AFR.REP"), Some((b"CF", b"CAF"))),
		name_and_abbreviation_for_country_revision_4(b"144", "Sri Lanka", Some(b"SRI LANKA"), Some((b"LK", b"LKA"))),
		name_and_abbreviation_for_country_revision_4(b"148", "Chad", Some(b"CHAD"), Some((b"TD", b"TCD"))),
		name_and_abbreviation_for_country_revision_4(b"152", "Chile", Some(b"CHILE"), Some((b"CH", b"CHL"))),
		name_and_abbreviation_for_country_revision_4(b"156", "China", Some(b"CHINA"), Some((b"CN", b"CHN"))),
		name_and_abbreviation_for_country_revision_4(b"158", "Taiwan Province of China", None, Some((b"TW", b"TWN"))),
		name_and_abbreviation_for_country_revision_4(b"170", "Colombia", Some(b"COLOMBIA"), Some((b"CO", b"COL"))),
		name_and_abbreviation_for_country_revision_4(b"174", "Comoros", Some(b"COMOROS"), Some((b"KM", b"COM"))),
		name_and_abbreviation_for_country_revision_4(b"178", "Congo", Some(b"CONGO"), Some((b"CG", b"COG"))),
		name_and_abbreviation_for_country_revision_4(b"180", "Democratic Republic of the Congo", Some(b"D.RP.CONGO"), Some((b"CD", b"COD"))),
		name_and_abbreviation_for_country_revision_4(b"184", "Cook Islands", Some(b"COOK IS"), Some((b"CK", b"COK"))),
		name_and_abbreviation_for_country_revision_4(b"188", "Costa Rica", Some(b"COSTA RICA"), Some((b"CR", b"CRI"))),
		name_and_abbreviation_for_country_revision_4(b"191", "Croatia", Some(b"CROATIA"), Some((b"HR", b"HRV"))),
		name_and_abbreviation_for_country_revision_4(b"192", "Cuba", Some(b"CUBA"), Some((b"CU", b"CUB"))),
		name_and_abbreviation_for_country_revision_4(b"196", "Cyprus", Some(b"CYPRUS"), Some((b"CY", b"CYP"))),
		name_and_abbreviation_for_country_revision_4(b"203", "Czech Republic", Some(b"CZECH REP"), Some((b"CZ", b"CZE"))),
		name_and_abbreviation_for_country_revision_4(b"204", "Benin", Some(b"BENIN"), Some((b"BJ", b"BEN"))),
		name_and_abbreviation_for_country_revision_4(b"208", "Denmark", Some(b"DENMARK"), Some((b"DK", b"DNK"))),
		name_and_abbreviation_for_country_revision_4(b"212", "Dominica", Some(b"DOMINICA"), Some((b"DM", b"DMA"))),
		name_and_abbreviation_for_country_revision_4(b"214", "Dominican Republic", Some(b"DOMINICAN RP"), Some((b"DO", b"DOM"))),
		name_and_abbreviation_for_country_revision_4(b"218", "Ecuador", Some(b"ECUADOR"), Some((b"EC", b"ECU"))),
		name_and_abbreviation_for_country_revision_4(b"222", "El Salvador", Some(b"EL SALVADOR"), Some((b"SV", b"SLV"))),
		name_and_abbreviation_for_country_revision_4(b"226", "Equatorial Guinea", Some(b"EQ.GUINEA"), Some((b"GQ", b"GNQ"))),
		name_and_abbreviation_for_country_revision_4(b"231", "Ethiopia", Some(b"ETHIOPIA"), Some((b"ET", b"ETH"))),
		name_and_abbreviation_for_country_revision_4(b"232", "Eritrea", Some(b"ERITREA"), Some((b"ER", b"ERI"))),
		name_and_abbreviation_for_country_revision_4(b"233", "Estonia", Some(b"ESTONIA"), Some((b"EE", b"EST"))),
		name_and_abbreviation_for_country_revision_4(b"234", "Faeroe Islands", Some(b"FAEROE IS"), Some((b"FO", b"FRO"))),
		name_and_abbreviation_for_country_revision_4(b"238", "Falkland Islands (Malvinas)", Some(b"FALKLAND IS"), Some((b"FK", b"FLK"))),
		name_and_abbreviation_for_country_revision_4(b"242", "Fiji", Some(b"FIJI"), Some((b"FJ", b"FJI"))),
		name_and_abbreviation_for_country_revision_4(b"246", "Finland", Some(b"FINLAND"), Some((b"FI", b"FIN"))),
		name_and_abbreviation_for_country_revision_4(b"250", "France", Some(b"FRANCE"), Some((b"FR", b"FRA"))),
		name_and_abbreviation_for_country_revision_4(b"254", "French Guiana", Some(b"FR.GUIANA"), Some((b"GF", b"GUF"))),
		name_and_abbreviation_for_country_revision_4(b"258", "French Polynesia", Some(b"FR.POLYNESIA"), Some((b"PF", b"PYF"))),
		name_and_abbreviation_for_country_revision_4(b"262", "Djibouti", Some(b"DJIBOUTI"), Some((b"DI", b"DJI"))),
		name_and_abbreviation_for_country_revision_4(b"266", "Gabon", Some(b"GABON"), Some((b"GA", b"GAB"))),
		name_and_abbreviation_for_country_revision_4(b"268", "Georgia", Some(b"GEORGIA"), Some((b"GE", b"GEO"))),
		name_and_abbreviation_for_country_revision_4(b"270", "Gambia", Some(b"GAMBIA"), Some((b"GM", b"GMB"))),
		name_and_abbreviation_for_country_revision_4(b"275", "Occupied Palestinian Territory", Some(b"OCC.PAL.TERR"), Some((b"PS", b"PSE"))),
		name_and_abbreviation_for_country_revision_4(b"276", "Germany", Some(b"GERMANY"), Some((b"DE", b"DEU"))),
		name_and_abbreviation_for_country_revision_4(b"286", "Ghana", Some(b"GHANA"), Some((b"GH", b"GHA"))),
		name_and_abbreviation_for_country_revision_4(b"292", "Gibraltar", Some(b"GIBRALTAR"), Some((b"GI", b"GIB"))),
		name_and_abbreviation_for_country_revision_4(b"296", "Kiribati", Some(b"KIRIBATI"), Some((b"KI", b"KIR"))),
		name_and_abbreviation_for_country_revision_4(b"300", "Greece", Some(b"GREECE"), Some((b"GR", b"GRC"))),
		name_and_abbreviation_for_country_revision_4(b"304", "Greenland", Some(b"GREENLAND"), Some((b"GL", b"GRL"))),
		name_and_abbreviation_for_country_revision_4(b"308", "Grenada", Some(b"GRENADA"), Some((b"GD", b"GRD"))),
		name_and_abbreviation_for_country_revision_4(b"312", "Guadeloupe", Some(b"GUADELOUPE"), Some((b"GP", b"GLP"))),
		name_and_abbreviation_for_country_revision_4(b"316", "Guam", Some(b"GUAM"), Some((b"GU", b"GUM"))),
		name_and_abbreviation_for_country_revision_4(b"320", "Guatemala", Some(b"GUATEMALA"), Some((b"GT", b"GTM"))),
		name_and_abbreviation_for_country_revision_4(b"324", "Guinea", Some(b"GUINEA"), Some((b"GN", b"GIN"))),
		name_and_abbreviation_for_country_revision_4(b"328", "Guyana", Some(b"GUYANA"), Some((b"GY", b"GUY"))),
		name_and_abbreviation_for_country_revision_4(b"332", "Haiti", Some(b"HAITI"), Some((b"HT", b"HTI"))),
		name_and_abbreviation_for_country_revision_4(b"336", "Holy See", Some(b"HOLY SEE"), Some((b"VA", b"VAT"))),
		name_and_abbreviation_for_country_revision_4(b"340", "Honduras", Some(b"HONDURAS"), Some((b"AN", b"HND"))),
		name_and_abbreviation_for_country_revision_4(b"344", "Hong Kong Special Administrative Region of China HONGKONG", Some(b"SAR"), Some((b"HK", b"HKG"))),
		name_and_abbreviation_for_country_revision_4(b"348", "Hungary", Some(b"HUNGARY"), Some((b"HU", b"HUN"))),
		name_and_abbreviation_for_country_revision_4(b"352", "Iceland", Some(b"ICELAND"), Some((b"IS", b"ISL"))),
		name_and_abbreviation_for_country_revision_4(b"356", "India", Some(b"INDIA"), Some((b"IN", b"IND"))),
		name_and_abbreviation_for_country_revision_4(b"360", "Indonesia", Some(b"INDONESIA"), Some((b"ID", b"IDN"))),
		name_and_abbreviation_for_country_revision_4(b"364", "Iran (Islamic Republic of)", Some(b"IRAN"), Some((b"IR", b"IRN"))),
		name_and_abbreviation_for_country_revision_4(b"368", "Iraq", Some(b"TRAQ"), Some((b"IQ", b"IRQ"))),
		name_and_abbreviation_for_country_revision_4(b"372", "Ireland", Some(b"IRELAND"), Some((b"IE", b"IRL"))),
		name_and_abbreviation_for_country_revision_4(b"376", "Israel", Some(b"ISRAEL"), Some((b"IL", b"ISR"))),
		name_and_abbreviation_for_country_revision_4(b"380", "Italy", Some(b"ITALY"), Some((b"IT", b"ITA"))),
		name_and_abbreviation_for_country_revision_4(b"384", "Céte d'Ivoire COTE", Some(b"DIVOIRE"), Some((b"CI", b"CIV"))),
		name_and_abbreviation_for_country_revision_4(b"388", "Jamaica", Some(b"JAMAICA"), Some((b"JM", b"JAM"))),
		name_and_abbreviation_for_country_revision_4(b"392", "Japan", Some(b"JAPAN"), Some((b"JP", b"JPN"))),
		name_and_abbreviation_for_country_revision_4(b"398", "Kazakhstan", Some(b"KAZAKHSTAN"), Some((b"KZ", b"KAZ"))),
		name_and_abbreviation_for_country_revision_4(b"400", "Jordan", Some(b"JORDAN"), Some((b"JO", b"JOR"))),
		name_and_abbreviation_for_country_revision_4(b"404", "Kenya", Some(b"KENYA"), Some((b"KE", b"KEN"))),
		name_and_abbreviation_for_country_revision_4(b"408", "Democratic People's Republic of Korea KOREA D", Some(b"P RP"), Some((b"KP", b"PRK"))),
		name_and_abbreviation_for_country_revision_4(b"410", "Republic of Korea", Some(b"KOREA REP."), Some((b"KR", b"KOR"))),
		name_and_abbreviation_for_country_revision_4(b"414", "Kuwait", Some(b"KUWAIT"), Some((b"KW", b"KWT"))),
		name_and_abbreviation_for_country_revision_4(b"417", "Kyrgyzstan", Some(b"KYRGYZSTAN"), Some((b"KG", b"KGZ"))),
		name_and_abbreviation_for_country_revision_4(b"418", "Lao People's Democratic Republic", Some(b"LAO P.DEM.R."), Some((b"LA", b"LAO"))),
		name_and_abbreviation_for_country_revision_4(b"422", "Lebanon", Some(b"LEBANON"), Some((b"LB", b"LBN"))),
		name_and_abbreviation_for_country_revision_4(b"426", "Lesotho", Some(b"LESOTHO"), Some((b"LS", b"LSO"))),
		name_and_abbreviation_for_country_revision_4(b"428", "Latvia", Some(b"LATVIA"), Some((b"LV", b"LVA"))),
		name_and_abbreviation_for_country_revision_4(b"430", "Liberia", Some(b"LIBERIA"), Some((b"LR", b"LBR"))),
		name_and_abbreviation_for_country_revision_4(b"434", "Libyan Arab Jamahiriya", Some(b"LIBYA"), Some((b"LY", b"LBY"))),
		name_and_abbreviation_for_country_revision_4(b"438", "Liechtenstein", Some(b"LIECHTENSTEN"), Some((b"LI", b"LIE"))),
		name_and_abbreviation_for_country_revision_4(b"440", "Lithuania", Some(b"LITHUANIA"), Some((b"LT", b"LTU"))),
		name_and_abbreviation_for_country_revision_4(b"442", "Luxembourg", Some(b"LUXEMBOURG"), Some((b"LU", b"LUX"))),
		name_and_abbreviation_for_country_revision_4(b"446", "Macau", Some(b"MACAU"), Some((b"MO", b"MAC"))),
		name_and_abbreviation_for_country_revision_4(b"450", "Madagascar", Some(b"MADAGASCAR"), Some((b"MG", b"MDG"))),
		name_and_abbreviation_for_country_revision_4(b"454", "Malawi", Some(b"MALAWI"), Some((b"MW", b"MWI"))),
		name_and_abbreviation_for_country_revision_4(b"458", "Malaysia", Some(b"MALAYSIA"), Some((b"MY", b"MYS"))),
		name_and_abbreviation_for_country_revision_4(b"462", "Maldives", Some(b"MALDIVES"), Some((b"MV", b"MDV"))),
		name_and_abbreviation_for_country_revision_4(b"466", "Mali", Some(b"MALI"), Some((b"ML", b"MUI"))),
		name_and_abbreviation_for_country_revision_4(b"470", "Malta", Some(b"MALTA"), Some((b"MT", b"MLT"))),
		name_and_abbreviation_for_country_revision_4(b"474", "Martinique", Some(b"MARTINIQUE"), Some((b"MQ", b"MTQ"))),
		name_and_abbreviation_for_country_revision_4(b"478", "Mauritania", Some(b"MAURITANTA"), Some((b"MR", b"MRT"))),
		name_and_abbreviation_for_country_revision_4(b"480", "Mauritius", Some(b"MAURITIUS"), Some((b"MU", b"MOS"))),
		name_and_abbreviation_for_country_revision_4(b"484", "Mexico", Some(b"MEXICO"), Some((b"MX", b"MEX"))),
		name_and_abbreviation_for_country_revision_4(b"492", "Monaco", Some(b"MONACO"), Some((b"MC", b"MCO"))),
		name_and_abbreviation_for_country_revision_4(b"496", "Mongolia", Some(b"MONGOLIA"), Some((b"MN", b"MNG"))),
		name_and_abbreviation_for_country_revision_4(b"498", "Republic of Moldova", Some(b"REP MOLDOVA"), Some((b"MD", b"MDA"))),
		name_and_abbreviation_for_country_revision_4(b"500", "Montserrat", Some(b"MONTSERRAT"), Some((b"MS", b"MSR"))),
		name_and_abbreviation_for_country_revision_4(b"504", "Morocco", Some(b"MOROCCO"), Some((b"MA", b"MAR"))),
		name_and_abbreviation_for_country_revision_4(b"508", "Mozambique", Some(b"MOZAMBIQUE"), Some((b"MZ", b"MOZ"))),
		name_and_abbreviation_for_country_revision_4(b"512", "Oman", Some(b"OMAN"), Some((b"OM", b"OMN"))),
		name_and_abbreviation_for_country_revision_4(b"516", "Namibia", Some(b"NAMIBIA"), Some((b"NA", b"NAM"))),
		name_and_abbreviation_for_country_revision_4(b"520", "Nauru", Some(b"NAURU"), Some((b"NR", b"NRU"))),
		name_and_abbreviation_for_country_revision_4(b"524", "Nepal", Some(b"NEPAL"), Some((b"NP", b"NPL"))),
		name_and_abbreviation_for_country_revision_4(b"528", "Netherlands", Some(b"NETHERLANDS"), Some((b"NL", b"NLD"))),
		name_and_abbreviation_for_country_revision_4(b"530", "Netherlands Antilles", Some(b"NETH.ANTILES"), Some((b"AN", b"ANT"))),
		name_and_abbreviation_for_country_revision_4(b"533", "Aruba", Some(b"ARUBA"), Some((b"AW", b"ABW"))),
		name_and_abbreviation_for_country_revision_4(b"540", "New Caledonia", Some(b"NEW CALEDNIA"), Some((b"NC", b"NCL"))),
		name_and_abbreviation_for_country_revision_4(b"548", "Vanuatu", Some(b"VANUATU"), Some((b"VU", b"VUT"))),
		name_and_abbreviation_for_country_revision_4(b"554", "New Zealand", Some(b"NEW ZEALAND"), Some((b"NZ", b"NZL"))),
		name_and_abbreviation_for_country_revision_4(b"558", "Nicaragua", Some(b"NICARAGUA"), Some((b"NI", b"NIC"))),
		name_and_abbreviation_for_country_revision_4(b"562", "Niger", Some(b"NIGER"), Some((b"NE", b"NER"))),
		name_and_abbreviation_for_country_revision_4(b"566", "Nigeria", Some(b"NIGERIA"), Some((b"NG", b"NGA"))),
		name_and_abbreviation_for_country_revision_4(b"570", "Niue", Some(b"NIUE"), Some((b"NU", b"NIU"))),
		name_and_abbreviation_for_country_revision_4(b"574", "Norfolk Island", Some(b"NORFOLK IS"), Some((b"NF", b"NFK"))),
		name_and_abbreviation_for_country_revision_4(b"578", "Norway", Some(b"NORWAY"), Some((b"NO", b"NOR"))),
		name_and_abbreviation_for_country_revision_4(b"580", "Northern Mariana Islands", Some(b"N.MARIANA IS"), Some((b"MP", b"MNP"))),
		name_and_abbreviation_for_country_revision_4(b"583", "Micronesia (Federated States of)", Some(b"MICRONESTA"), Some((b"FM", b"FSM"))),
		name_and_abbreviation_for_country_revision_4(b"584", "Marshall Islands", Some(b"MARSHALL IS"), Some((b"MH", b"MHL"))),
		name_and_abbreviation_for_country_revision_4(b"585", "Palau", Some(b"PALAU"), Some((b"PW", b"PLW"))),
		name_and_abbreviation_for_country_revision_4(b"586", "Pakistan", Some(b"PAKISTAN"), Some((b"PK", b"PAK"))),
		name_and_abbreviation_for_country_revision_4(b"591", "Panama", Some(b"PANAMA"), Some((b"PA", b"PAN"))),
		name_and_abbreviation_for_country_revision_4(b"598", "Papua New Guinea", Some(b"PAPUA N.GUIN"), Some((b"PG", b"PNG"))),
		name_and_abbreviation_for_country_revision_4(b"600", "Paraguay", Some(b"PARAGUAY"), Some((b"PY", b"PRY"))),
		name_and_abbreviation_for_country_revision_4(b"604", "Peru", Some(b"PERU"), Some((b"PE", b"PER"))),
		name_and_abbreviation_for_country_revision_4(b"608", "Philippines", Some(b"PHILIPPINES"), Some((b"PH", b"PHL"))),
		name_and_abbreviation_for_country_revision_4(b"612", "Pitcairn", Some(b"PITCAIRN"), Some((b"PN", b"PCN"))),
		name_and_abbreviation_for_country_revision_4(b"616", "Poland", Some(b"POLAND"), Some((b"PL", b"POL"))),
		name_and_abbreviation_for_country_revision_4(b"620", "Portugal", Some(b"PORTUGAL"), Some((b"PT", b"PRT"))),
		name_and_abbreviation_for_country_revision_4(b"624", "Guinea-Bissau", Some(b"GUINEABISSAU"), Some((b"GW", b"GNB"))),
		name_and_abbreviation_for_country_revision_4(b"626", "East Timor", Some(b"EAST TIMOR"), Some((b"TP", b"TMP"))),
		name_and_abbreviation_for_country_revision_4(b"630", "Puerto Rico", Some(b"PUERTO RICO"), Some((b"PR", b"PRI"))),
		name_and_abbreviation_for_country_revision_4(b"634", "Qatar", Some(b"QATAR"), Some((b"OA", b"QAT"))),
		name_and_abbreviation_for_country_revision_4(b"638", "Réunion", Some(b"REUNION"), Some((b"RE", b"REU"))),
		name_and_abbreviation_for_country_revision_4(b"642", "Romania", Some(b"ROMANIA"), Some((b"RO", b"ROM"))),
		name_and_abbreviation_for_country_revision_4(b"643", "Russian Federation", Some(b"RUSSIAN FED"), Some((b"RU", b"RUS"))),
		name_and_abbreviation_for_country_revision_4(b"646", "Rwanda", Some(b"RWANDA"), Some((b"RW", b"RWA"))),
		name_and_abbreviation_for_country_revision_4(b"654", "Saint Helena", Some(b"ST.HELENA"), Some((b"SH", b"SRN"))),
		name_and_abbreviation_for_country_revision_4(b"659", "Saint Kitts and Nevis", Some(b"ST.KITTS-NEV"), Some((b"KN", b"KNA"))),
		name_and_abbreviation_for_country_revision_4(b"660", "Anguilla", Some(b"ANGUILLA"), Some((b"AI", b"AIA"))),
		name_and_abbreviation_for_country_revision_4(b"662", "Saint Lucia", Some(b"ST.LUCIA"), Some((b"LC", b"LCA"))),
		name_and_abbreviation_for_country_revision_4(b"666", "Saint Pierre and Miquelon", Some(b"ST.PIERRE,MQ"), Some((b"PM", b"SPM"))),
		name_and_abbreviation_for_country_revision_4(b"670", "Saint Vincent and the Grenadines", Some(b"ST.VINCENT,G"), Some((b"VC", b"VCT"))),
		name_and_abbreviation_for_country_revision_4(b"674", "San Marino", Some(b"SAN MARINO"), Some((b"SM", b"SMR"))),
		name_and_abbreviation_for_country_revision_4(b"678", "Sao Tome and Principe", Some(b"SAO TOME PRN"), Some((b"ST", b"STP"))),
		name_and_abbreviation_for_country_revision_4(b"682", "Saudi Arabia", Some(b"SAUDI ARABIA"), Some((b"SA", b"SAU"))),
		name_and_abbreviation_for_country_revision_4(b"686", "Senegal", Some(b"SENEGAL"), Some((b"SN", b"SEN"))),
		name_and_abbreviation_for_country_revision_4(b"690", "Seychelles", Some(b"SEYCHELLES"), Some((b"SC", b"SYC"))),
		name_and_abbreviation_for_country_revision_4(b"694", "Sierra Leone", Some(b"SIERRA LEONE"), Some((b"SL", b"SLE"))),
		name_and_abbreviation_for_country_revision_4(b"702", "Singapore", Some(b"SINGAPORE"), Some((b"SG", b"SGP"))),
		name_and_abbreviation_for_country_revision_4(b"703", "Slovakia", Some(b"SLOVAKIA"), Some((b"SK", b"SVK"))),
		name_and_abbreviation_for_country_revision_4(b"704", "Viet Nam", Some(b"VIET NAM"), Some((b"VN", b"VNM"))),
		name_and_abbreviation_for_country_revision_4(b"705", "Slovenia", Some(b"SLOVENIA"), Some((b"SI", b"SVN"))),
		name_and_abbreviation_for_country_revision_4(b"706", "Somalia", Some(b"SOMALIA"), Some((b"SO", b"SOM"))),
		name_and_abbreviation_for_country_revision_4(b"710", "South Africa", Some(b"SOUTH AFRICA"), Some((b"ZA", b"ZAF"))),
		name_and_abbreviation_for_country_revision_4(b"716", "Zimbabwe", Some(b"ZIMBABWE"), Some((b"ZW", b"ZWE"))),
		name_and_abbreviation_for_country_revision_4(b"724", "Spain", Some(b"SPAIN"), Some((b"ES", b"ESP"))),
		name_and_abbreviation_for_country_revision_4(b"732", "Western Sahara", Some(b"WESTN.SAHARA"), Some((b"EH", b"ESH"))),
		name_and_abbreviation_for_country_revision_4(b"736", "Sudan", Some(b"SUDAN"), Some((b"SO", b"SDN"))),
		name_and_abbreviation_for_country_revision_4(b"740", "Suriname", Some(b"SURINAME"), Some((b"SR", b"SUR"))),
		name_and_abbreviation_for_country_revision_4(b"744", "Svalbard and Jan Mayen Islands", Some(b"SVALBARD IS"), Some((b"SJ", b"SJM"))),
		name_and_abbreviation_for_country_revision_4(b"748", "Swaziland", Some(b"SWAZILAND"), Some((b"SZ", b"SWZ"))),
		name_and_abbreviation_for_country_revision_4(b"752", "Sweden", Some(b"SWEDEN"), Some((b"SE", b"SWE"))),
		name_and_abbreviation_for_country_revision_4(b"756", "Switzerland", Some(b"SWITZERLAND"), Some((b"CH", b"CHE"))),
		name_and_abbreviation_for_country_revision_4(b"760", "Syrian Arab Republic", Some(b"SYRIA"), Some((b"SY", b"SYR"))),
		name_and_abbreviation_for_country_revision_4(b"762", "Tajikistan", Some(b"TAJIKISTAN"), Some((b"TJ", b"TIK"))),
		name_and_abbreviation_for_country_revision_4(b"764", "Thailand", Some(b"THAILAND"), Some((b"TH", b"THA"))),
		name_and_abbreviation_for_country_revision_4(b"768", "Togo", Some(b"TOGO"), Some((b"TG", b"TGO"))),
		name_and_abbreviation_for_country_revision_4(b"772", "Tokelau", Some(b"TOKELAU"), Some((b"TK", b"TKL"))),
		name_and_abbreviation_for_country_revision_4(b"776", "Tonga", Some(b"TONGA"), Some((b"TO", b"TON"))),
		name_and_abbreviation_for_country_revision_4(b"780", "Trinidad and Tobago", Some(b"TRINIDAD TBG"), Some((b"TT", b"TTO"))),
		name_and_abbreviation_for_country_revision_4(b"784", "United Arab Emirates", Some(b"UNTD ARAB EM"), Some((b"AE", b"ARE"))),
		name_and_abbreviation_for_country_revision_4(b"788", "Tunisia", Some(b"TUNISIA"), Some((b"IN", b"TUN"))),
		name_and_abbreviation_for_country_revision_4(b"792", "Turkey", Some(b"TURKEY"), Some((b"TR", b"TUR"))),
		name_and_abbreviation_for_country_revision_4(b"795", "Turkmenistan", Some(b"TURKMENISTAN"), Some((b"TM", b"TKM"))),
		name_and_abbreviation_for_country_revision_4(b"796", "Turks and Caicos Islands", Some(b"TURKS,CAICOS"), Some((b"TC", b"TCA"))),
		name_and_abbreviation_for_country_revision_4(b"798", "Tuvalu", Some(b"TUVALU"), Some((b"TV", b"TUV"))),
		name_and_abbreviation_for_country_revision_4(b"800", "Uganda", Some(b"UGANDA"), Some((b"UG", b"UGA"))),
		name_and_abbreviation_for_country_revision_4(b"804", "Ukraine", Some(b"UKRAINE"), Some((b"VA", b"UKR"))),
		name_and_abbreviation_for_country_revision_4(b"807", "The former Yugoslav Republic of Macedonia", Some(b"TFYROM"), Some((b"MK", b"MKD"))),
		name_and_abbreviation_for_country_revision_4(b"818", "Egypt", Some(b"EGYPT"), Some((b"EG", b"EGY"))),
		name_and_abbreviation_for_country_revision_4(b"826", "United Kingdom", Some(b"UK"), Some((b"GB", b"GBR"))),
		name_and_abbreviation_for_country_revision_4(b"830", "Channel Islands", Some(b"CHANNEL IS"), None),
		name_and_abbreviation_for_country_revision_4(b"833", "Isle of Man", Some(b"ISLE OF MAN"), Some((b"IM", b"IMY"))),
		name_and_abbreviation_for_country_revision_4(b"834", "United Republic of Tanzania", Some(b"TANZANIA"), Some((b"TZ", b"TZA"))),
		name_and_abbreviation_for_country_revision_4(b"840", "United States", Some(b"USA"), Some((b"US", b"USA"))),
		name_and_abbreviation_for_country_revision_4(b"850", "United States Virgin Islands", Some(b"US.VIRGIN IS"), Some((b"VI", b"VIR"))),
		name_and_abbreviation_for_country_revision_4(b"854", "Burkina Faso", Some(b"BURKINA FASO"), Some((b"BF", b"BFA"))),
		name_and_abbreviation_for_country_revision_4(b"858", "Uruguay", Some(b"URUGUAY"), Some((b"UY", b"URY"))),
		name_and_abbreviation_for_country_revision_4(b"860", "Uzbekistan", Some(b"UZBEKISTAN"), Some((b"UZ", b"UZB"))),
		name_and_abbreviation_for_country_revision_4(b"862", "Venezuela", Some(b"VENEZUELA"), Some((b"VE", b"VEN"))),
		name_and_abbreviation_for_country_revision_4(b"876", "Wallis and Futuna Islands", Some(b"WALLIS FUT.I"), Some((b"WF", b"WLF"))),
		name_and_abbreviation_for_country_revision_4(b"882", "Samoa", Some(b"SAMOA"), Some((b"WS", b"WSM"))),
		name_and_abbreviation_for_country_revision_4(b"887", "Yemen", Some(b"YEMEN"), Some((b"YE", b"YEM"))),
		name_and_abbreviation_for_country_revision_4(b"891", "Yugoslavia", Some(b"YUGOSLAVIA"), Some((b"YU", b"YUG"))),
		name_and_abbreviation_for_country_revision_4(b"894", "Zambia", Some(b"ZAMBIA"), Some((b"ZM", b"ZMB"))),
		name_and_abbreviation_for_country_revision_4(b"896", "Areas not elsewhere specified", Some(b"N.E.S."), None),
		name_and_abbreviation_for_country_revision_4(b"898", "Areas not specified", Some(b"N.S."), None),
	]
};
